In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('7_36.csv', header=None)

In [3]:
from sklearn.decomposition import PCA

In [4]:
pca = PCA(n_components=2)

In [5]:
transformed_features = pca.fit_transform(df)

In [6]:
transformed_features[0]

array([-14.27903089, -16.39322252])

In [7]:
explained_variance = np.round(np.cumsum(pca.explained_variance_ratio_),3)
explained_variance

array([0.365, 0.654])

In [14]:
pca = PCA(n_components=3, svd_solver='auto')
pca.fit(df)
explained_variance = np.round(np.cumsum(pca.explained_variance_ratio_),3)
explained_variance

array([0.365, 0.654, 0.874])

In [18]:
import seaborn as sns

In [ ]:
sns.scatterplot(
    x=transformed_features[:, 0],
    y=transformed_features[:, 1]
)